### ISSUE TITLE
better room search

### ISSUE THREAD

**Issue by Julius-Babies** [Julius-Babies/VPlanPlus#153]
## Tasks
- [x] Fix room names wrap (33992cb3ce5ca4877ac3caa097fb78f78270f24f)
- [x] Fix crash when not in class profile (e8363b06003d52805e6cb738c41806a13755a9e6)
- [X] Add ability to click on used room to see more info (26b75896401831661da3be39032f03b9531a049b)
